[package]
name = "probe-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "_probe"
crate-type = ["cdylib"]

[dependencies]
probe = {path = "../", default-features = false}
pyo3 = {version = "0.21.2", features = ["extension-module", "abi3", "abi3-py37"]}
